/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const WallOfFameEntry = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
});

export const idlService = IDL.Service({
  'addEntry' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'generateId' : IDL.Func([], [IDL.Nat], []),
  'getAllEntries' : IDL.Func([], [IDL.Vec(WallOfFameEntry)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const WallOfFameEntry = IDL.Record({ 'id' : IDL.Nat, 'name' : IDL.Text });
  
  return IDL.Service({
    'addEntry' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'generateId' : IDL.Func([], [IDL.Nat], []),
    'getAllEntries' : IDL.Func([], [IDL.Vec(WallOfFameEntry)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };